[package]
edition = "2021"
name = "pcc-search"
version = "0.1.0"

[dependencies]
# Local crates
pcc-common = {path = "../common"}
pcc-kdtree = {path = "../kdtree"}
pcc-octree = {path = "../octree"}
# External crates
nalgebra = "0"
num = "0"
