[package]
edition = "2021"
name = "pcc-io"
version = "0.1.0"

[dependencies]
# Local crates
pcc-common = {path = "../common"}
# External crates
log = "0"
nalgebra = "0"
num = "0"

[dev-dependencies]
tempfile = "3"
