[package]
edition = "2021"
name = "pcc-kdtree"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Local crates
pcc-common = {path = "../common"}
# External crates
bitvec = "1"
nalgebra = "0"
