[package]
edition = "2021"
name = "pcc-sac"
version = "0.1.0"

[dependencies]
# Local crates
pcc-common = {path = "../common"}
# External crates
nalgebra = "0"
num = "0"
rand = "0"
sample-consensus = "1"
