[package]
edition = "2021"
name = "pcc-features"
version = "0.1.0"

[dependencies]
# Local crates
pcc-common = {path = "../common"}
pcc-search = {path = "../search"}
# External crates
nalgebra = "0"
num = "0"
