[package]
edition = "2021"
name = "pcc-filters"
version = "0.1.0"

[dependencies]
# Local crates
pcc-common = {path = "../common"}
pcc-kdtree = {path = "../kdtree"}
pcc-sac = {path = "../sac"}
# External crates
nalgebra = "0"
num = "0"
rand = "0"
rayon = "1"
